name: test
on: 
  push:
    branches:
      - main

jobs:
  install-and-connect:
    runs-on:  ubuntu-latest
      

    steps:
      - name: list
        run: ls -la
      - name: ps
        run: ps -aux
        
